package co.edu.icesi.PlataformaBanco.modelo;
// Generated 10/04/2018 03:15:32 PM by Hibernate Tools 5.2.8.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transferencias generated by hbm2java
 */
@Entity
@Table(name = "transferencias", schema = "public")
public class Transferencias implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -307620557445035732L;
	private TransferenciasId id;
	private Cuentas cuentasByOrigenCueNumero;
	private Cuentas cuentasByDestinoCueNumero;
	private Long usuCedula;
	private BigDecimal tranValor;
	private Date tranFecha;
	private String tranDescripcion;

	public Transferencias() {
	}

	public Transferencias(TransferenciasId id, Cuentas cuentasByOrigenCueNumero, Cuentas cuentasByDestinoCueNumero,
			BigDecimal tranValor, Date tranFecha, String tranDescripcion) {
		this.id = id;
		this.cuentasByOrigenCueNumero = cuentasByOrigenCueNumero;
		this.cuentasByDestinoCueNumero = cuentasByDestinoCueNumero;
		this.tranValor = tranValor;
		this.tranFecha = tranFecha;
		this.tranDescripcion = tranDescripcion;
	}

	public Transferencias(TransferenciasId id, Cuentas cuentasByOrigenCueNumero, Cuentas cuentasByDestinoCueNumero,
			Long usuCedula, BigDecimal tranValor, Date tranFecha, String tranDescripcion) {
		this.id = id;
		this.cuentasByOrigenCueNumero = cuentasByOrigenCueNumero;
		this.cuentasByDestinoCueNumero = cuentasByDestinoCueNumero;
		this.usuCedula = usuCedula;
		this.tranValor = tranValor;
		this.tranFecha = tranFecha;
		this.tranDescripcion = tranDescripcion;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "tranCodigo", column = @Column(name = "tran_codigo", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "origenCueNumero", column = @Column(name = "origen_cue_numero", nullable = false, length = 30)),
			@AttributeOverride(name = "destinoCueNumero", column = @Column(name = "destino_cue_numero", nullable = false, length = 30)) })
	public TransferenciasId getId() {
		return this.id;
	}

	public void setId(TransferenciasId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "origen_cue_numero", nullable = false, insertable = false, updatable = false)
	public Cuentas getCuentasByOrigenCueNumero() {
		return this.cuentasByOrigenCueNumero;
	}

	public void setCuentasByOrigenCueNumero(Cuentas cuentasByOrigenCueNumero) {
		this.cuentasByOrigenCueNumero = cuentasByOrigenCueNumero;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "destino_cue_numero", nullable = false, insertable = false, updatable = false)
	public Cuentas getCuentasByDestinoCueNumero() {
		return this.cuentasByDestinoCueNumero;
	}

	public void setCuentasByDestinoCueNumero(Cuentas cuentasByDestinoCueNumero) {
		this.cuentasByDestinoCueNumero = cuentasByDestinoCueNumero;
	}

	@Column(name = "usu_cedula", precision = 10, scale = 0)
	public Long getUsuCedula() {
		return this.usuCedula;
	}

	public void setUsuCedula(Long usuCedula) {
		this.usuCedula = usuCedula;
	}

	@Column(name = "tran_valor", nullable = false, precision = 10)
	public BigDecimal getTranValor() {
		return this.tranValor;
	}

	public void setTranValor(BigDecimal tranValor) {
		this.tranValor = tranValor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "tran_fecha", nullable = false, length = 29)
	public Date getTranFecha() {
		return this.tranFecha;
	}

	public void setTranFecha(Date tranFecha) {
		this.tranFecha = tranFecha;
	}

	@Column(name = "tran_descripcion", nullable = false, length = 50)
	public String getTranDescripcion() {
		return this.tranDescripcion;
	}

	public void setTranDescripcion(String tranDescripcion) {
		this.tranDescripcion = tranDescripcion;
	}

}
