package co.edu.icesi.PlataformaBanco.modelo;
// Generated 10/04/2018 03:15:32 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TransferenciasId generated by hbm2java
 */
@Embeddable
public class TransferenciasId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7018078930967253134L;
	private long tranCodigo;
	private String origenCueNumero;
	private String destinoCueNumero;

	public TransferenciasId() {
	}

	public TransferenciasId(long tranCodigo, String origenCueNumero, String destinoCueNumero) {
		this.tranCodigo = tranCodigo;
		this.origenCueNumero = origenCueNumero;
		this.destinoCueNumero = destinoCueNumero;
	}

	@Column(name = "tran_codigo", nullable = false, precision = 10, scale = 0)
	public long getTranCodigo() {
		return this.tranCodigo;
	}

	public void setTranCodigo(long tranCodigo) {
		this.tranCodigo = tranCodigo;
	}

	@Column(name = "origen_cue_numero", nullable = false, length = 30)
	public String getOrigenCueNumero() {
		return this.origenCueNumero;
	}

	public void setOrigenCueNumero(String origenCueNumero) {
		this.origenCueNumero = origenCueNumero;
	}

	@Column(name = "destino_cue_numero", nullable = false, length = 30)
	public String getDestinoCueNumero() {
		return this.destinoCueNumero;
	}

	public void setDestinoCueNumero(String destinoCueNumero) {
		this.destinoCueNumero = destinoCueNumero;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TransferenciasId))
			return false;
		TransferenciasId castOther = (TransferenciasId) other;

		return (this.getTranCodigo() == castOther.getTranCodigo())
				&& ((this.getOrigenCueNumero() == castOther.getOrigenCueNumero())
						|| (this.getOrigenCueNumero() != null && castOther.getOrigenCueNumero() != null
								&& this.getOrigenCueNumero().equals(castOther.getOrigenCueNumero())))
				&& ((this.getDestinoCueNumero() == castOther.getDestinoCueNumero())
						|| (this.getDestinoCueNumero() != null && castOther.getDestinoCueNumero() != null
								&& this.getDestinoCueNumero().equals(castOther.getDestinoCueNumero())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getTranCodigo();
		result = 37 * result + (getOrigenCueNumero() == null ? 0 : this.getOrigenCueNumero().hashCode());
		result = 37 * result + (getDestinoCueNumero() == null ? 0 : this.getDestinoCueNumero().hashCode());
		return result;
	}

}
